<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro"
>


<xacro:property name="base_length" value="0.40"/>
<xacro:property name="base_width" value="0.26"/>
<xacro:property name="base_height" value="0.193"/>
<xacro:property name="base_height_from_earth" value="0.261"/>
<xacro:property name="bar_width" value="0.03"/>
<xacro:property name="vertical_bar_height" value="1.33"/>

<!-- Chassis -->
	<link name="base_link">
		<inertial>
			<mass value="10.0"/>
			<origin xyz="0 0 0.177"/>
			<inertia ixx="0.3338" ixy="0.0" ixz="0.0"
				 iyy="0.4783" iyz="0.0"
				 izz="0.3338"/>
		</inertial>
		<visual name="base_visual">
			<origin xyz="0 0 0.177" rpy="0 0 0"/>
			<geometry name="pioneer_geom">
				<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/p3at_meshes/chassis.dae"/>
			</geometry>
			<material name="ChassisRed">
				<color rgba="0.851 0.0 0.0 1.0"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0.177" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/p3at_meshes/chassis.dae"/>
				</geometry>
		</collision>
	</link>
	<gazebo reference="base_link">
		<material>Gazebo/Red</material>
	</gazebo>

<!-- Top -->
	<link name="top_plate">
		<inertial>
			<mass value="0.1"/>	
			<origin xyz="-0.025 0 -0.223"/>
			<inertia ixx="1.0" ixy="0.0" ixz="0.0"
				 iyy="1.0" iyz="0.0"
 				izz="1.0"/>
		</inertial>
		<visual name="base_visual">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry name="pioneer_geom">
				<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/p3at_meshes/top.dae"/>
			</geometry>
			<material name="TopBlack">
					<color rgba="0.038 0.038 0.038 1.0"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0 0 0"/>
			</geometry>
		</collision>
	</link>
	<gazebo reference="top_plate">
		<material>Gazebo/Black</material>
	</gazebo>

	<joint name="base_top_joint" type="fixed">
		<origin xyz="0.003 0 0.274" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="top_plate"/>
	</joint>

<!--Front laser -->
	<link name="laser_scan_link" type="laser"> 
		<inertial> 
			<mass value="0.5" /> 
			<origin xyz="0 0 0" /> 
			<inertia ixx="0.3"  ixy="0.3"  ixz="0.3" iyy="0.3"  iyz="0.3"  izz="0.3" /> 
		</inertial> 
		<visual> 
			<origin xyz="0 0 0" rpy="0 0 0"/> 
			<geometry> 
				<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/hokuyo.dae"/>
			</geometry> 
		</visual> 
		<collision> 
			<origin xyz="0 0 0" rpy="0 0 0"/> 
			<geometry> 
				<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/hokuyo.dae"/>
			</geometry> 
		</collision> 
	</link> 

	<joint name="laser_to_base_link" type="fixed"> 
		<origin xyz="0.25 0 0.32" rpy="0 0 0" /> 
		<parent link="base_link" /> 
		<child link="laser_scan_link"/> 
	</joint>

	<gazebo reference="laser_scan_link">
    	<sensor type="ray" name="head_hokuyo_sensor">
      		<pose>0 0 0 0 0 0</pose>
      		<visualize>false</visualize>
      		<update_rate>40</update_rate>
			<ray>
				<scan>
				<horizontal>
					<samples>720</samples>
					<resolution>1</resolution>
					<min_angle>-1.570796</min_angle>
					<max_angle>1.570796</max_angle>
				</horizontal>
				</scan>
				<range>
				<min>0.10</min>
				<max>30.0</max>
				<resolution>0.01</resolution>
				</range>
				<noise>
				<type>gaussian</type>
				<mean>0.0</mean>
				<stddev>0.01</stddev>
				</noise>
			</ray>
      		<plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
        		<topicName>/p3at/laser/scan</topicName>
        		<frameName>laser_scan_link</frameName>
      		</plugin>
    	</sensor>
	</gazebo>

<!-- VERTICAL + HORIZONTAL BARS -->
	<xacro:macro name="vertical_bar" params="src_frame name right">
		<link name="vertical_bar_${name}">
			<inertial> 
				<mass value="0.5" /> 
				<origin xyz="0 0 0" /> 
				<inertia ixx="0.3"  ixy="0.3"  ixz="0.3" iyy="0.3"  iyz="0.3"  izz="0.3" /> 
			</inertial>
			<visual>
				<geometry>
					<box size="${bar_width} ${bar_width} ${vertical_bar_height}"/>
				</geometry>
				<material name="gray"/>
				<origin rpy="0 0 0" xyz="0 0 ${vertical_bar_height / 2}"/>
			</visual>
		</link>
		<joint name="vertical_bar_${name}_joint" type="fixed">
			<origin rpy="0 0 0" xyz="0 ${(base_width / 2 + bar_width / 2) * right} ${base_height}"/>
			<parent link="${src_frame}"/>
			<child link="vertical_bar_${name}"/>
		</joint>
		<gazebo reference="vertical_bar_${name}">
			<material>Gazebo/Grey</material>
		</gazebo>
	</xacro:macro>

	<xacro:macro name="horizontal_bar" params="src_frame name length origin_x origin_y origin_z rpy">
		<link name="horizontal_bar_${name}">
			<visual>
				<geometry>
					<box size="${bar_width} ${length} ${bar_width}"/>
				</geometry>
				<material name="gray"/>
				<origin rpy="0 0 0" xyz="0 0 0"/>
			</visual>
		</link>
		<joint name="horizontal_bar_${name}_joint" type="fixed">
			<origin rpy="${rpy}" xyz="${origin_x} ${origin_y} ${origin_z}"/>
			<parent link="${src_frame}"/>
			<child link="horizontal_bar_${name}"/>
		</joint>
		<gazebo reference="horizontal_bar_${name}">
			<material>Gazebo/Grey</material>
		</gazebo>
	</xacro:macro>

	<xacro:macro name="horizontal_bar_with_object" params="src_frame bar_length bar_origin_x bar_origin_y bar_origin_z over object_joint_y right child_link rpy">
		<xacro:horizontal_bar src_frame="${src_frame}" name="${child_link}" length="${bar_length}" origin_x="${bar_origin_x}" origin_y="${bar_origin_y}" origin_z="${bar_origin_z}" rpy="${rpy}"/>
		<joint name="${child_link}_joint" type="fixed">
			<origin rpy="0 0 0" xyz="${right * bar_width / 2} ${object_joint_y} ${over * bar_width / 2}"/>
			<parent link="horizontal_bar_${child_link}"/>
			<child link="${child_link}_link"/>
		</joint>
	</xacro:macro>

	<xacro:vertical_bar src_frame="base_link" name="dx" right="1"/>
	<xacro:vertical_bar src_frame="base_link" name="sx" right="-1"/>
	<xacro:include filename="$(find p3at_gazebo)/defs/kinect.xacro" />
	
	<xacro:kinect name="kinect" frame_name="openni_camera"/>
	<xacro:horizontal_bar_with_object src_frame="base_link" bar_length="${base_width + bar_width}" bar_origin_x="0" bar_origin_y="0" bar_origin_z="${base_height + 3 * vertical_bar_height / 4}" rpy="0 0 0" over="0" right="1" object_joint_y="0" child_link="kinect"/>

<!-- IMU -->

	<link name="imu">
		<visual>
			<geometry>
				<box size="0.05 0.035 0.02"/>
			</geometry>
      <material name="orange"/>
      <color rgba="1 0.55 0 1"/>
			<origin rpy="0 0 0" xyz="0.13 -0.135 0.46"/>
		</visual>
	</link>	

  <joint name="imu_link_joint" type="fixed">
    <parent link="base_link" />
    <child link="imu"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <gazebo reference="imu">
    <gravity>true</gravity>
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <topic>imu</topic>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <topicName>imu</topicName>
        <bodyName>imu</bodyName>
        <updateRateHZ>10.0</updateRateHZ>
        <gaussianNoise>0.0</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>imu</frameName>
      </plugin>
      <pose>0 0 0 0 0 0</pose>
    </sensor>
  </gazebo>

<!-- Front + Back Sonar -->
	<link name="front_sonar">
		<inertial>
			<mass value="0.1"/>	
			<origin xyz="0 0 0"/>
			<inertia ixx="1.0" ixy="0.0" ixz="0.0"
				 iyy="1.0" iyz="0.0" izz="1.0"/>
		</inertial>
		<visual name="base_visual">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry name="pioneer_geom">
				<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/p3at_meshes/front_sonar.dae"/>
			</geometry>
			<material name="SonarYellow">
				<color rgba="0.715 0.583 0.210 1.0"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0 0 0"/>
			</geometry>
		</collision>
	</link>
	<gazebo reference="front_sonar">
		<material value="Gazebo/Yellow"/>
	</gazebo>

	<joint name="base_front_joint" type="fixed">
		<origin xyz="0.193 0 0.25" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="front_sonar"/>
	</joint>

	<link name="back_sonar">
		<inertial>
			<mass value="0.1"/>	
			<origin xyz="0 0 0"/>
			<inertia ixx="1.0" ixy="0.0" ixz="0.0"
				 iyy="1.0" iyz="0.0" izz="1.0"/>
		</inertial>
		<visual name="base_visual">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry name="pioneer_geom">
				<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/p3at_meshes/back_sonar.dae"/>
			</geometry>
			<material name="SonarYellow">
				<color rgba="0.715 0.583 0.210 1.0"/>
			</material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0 0 0"/>
			</geometry>
		</collision>
	</link>
	<gazebo reference="back_sonar">
		<material value="Gazebo/Yellow"/>
	</gazebo>

	<joint name="base_back_joint" type="fixed">
		<origin xyz="-0.187 0 0.247" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="back_sonar"/>
	</joint>

<!-- Front Axles + Wheels + Hubcaps -->
<xacro:macro name="p3at_front" params="suffix reflect">
	<link name="p3at_front_${suffix}_axle">
		<inertial>
			<mass value="0.1"/>	
			<origin xyz="0 0 0"/>
			<inertia ixx="1.0" ixy="0.0" ixz="0.0"
				 iyy="1.0" iyz="0.0" izz="1.0"/>
  	 	</inertial>
	<visual name="base_visual">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry name="pioneer_geom">
			<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/p3at_meshes/axle.dae"/>
		</geometry>
		<material name="AxleGrey">
			<color rgba="0.5 0.5 0.5 1"/>
		</material>
	</visual>
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="0 0 0"/>
		</geometry>
	</collision>
	</link>
	<gazebo reference="p3at_front_${suffix}_axle">
		<material value="Gazebo/Grey"/>
	</gazebo>

	<joint name="base_front_${suffix}_axle_joint" type="fixed">
		<origin xyz="0.135 ${reflect*0.156} 0.111" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="p3at_front_${suffix}_axle"/>
	</joint>

	<link name="p3at_front_${suffix}_hub">
		<inertial>
			<mass value="0.1"/>	
			<origin xyz="0 0 0"/>
			<inertia ixx="1.0" ixy="0.0" ixz="0.0"
				 iyy="1.0" iyz="0.0" izz="1.0"/>
  	 	</inertial>
	<visual name="base_visual">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry name="pioneer_geom">
			<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/p3at_meshes/${suffix}_hubcap.dae"/>
		</geometry>
		<material name="HubcapYellow">
			<color rgba="1.0 0.811 0.151 1.0"/>
		</material>
	</visual>
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="0 0 0"/>
		</geometry>
	</collision>
	</link>
	<gazebo reference="p3at_front_${suffix}_hub">
		<material value="Gazebo/Yellow"/>
	</gazebo>

	<joint name="base_front_${suffix}_hub_joint" type="fixed">
		<origin xyz="0 ${reflect*0.041} 0" rpy="0 0 0"/>
		<parent link="p3at_front_${suffix}_axle"/>
		<child link="p3at_front_${suffix}_hub"/>
	</joint>

	<link name="p3at_front_${suffix}_wheel">
		<inertial>
			<mass value="0.5"/>	
			<origin xyz="0 0 0"/>
			<inertia ixx="0.012411765597" ixy="0" ixz="0"
         iyy="0.015218160428" iyz="0" izz="0.011763977943"/>
      </inertial>
	<visual name="base_visual">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry name="pioneer_geom">
			<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/p3at_meshes/wheel.dae"/>
		</geometry>
		<material name="WheelBlack">
			<color rgba="0.117 0.117 0.117 1"/>
		</material>
	</visual>
	<collision>
		<origin xyz="0 0 0" rpy="${-3.1415927/2} 0 0"/>
		<geometry>
	    <!--mesh filename="package://p3at_gazebo/meshes/p3at_meshes/wheel.stl"/-->
	    <cylinder radius="0.111" length="0.075"/>
		</geometry>
	</collision>
	</link>
	<gazebo reference="p3at_front_${suffix}_wheel">
		<material value="Gazebo/Black"/>
	</gazebo>

	<joint name="p3at_front_${suffix}_wheel_joint" type="continuous">
  	<axis xyz="0 1 0"/>
    <anchor xyz="0 0 0"/>
    <limit effort="100" velocity="100" />
    <joint_properties damping="0.7"/>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<parent link="p3at_front_${suffix}_hub"/>
		<child link="p3at_front_${suffix}_wheel"/>
	</joint>

	<transmission name="p3at_front_${suffix}_wheel_tran">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="p3at_front_${suffix}_wheel_joint">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="p3at_front_${suffix}_wheel_motor">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
		<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
</xacro:macro>
<!-- Back Axles + Wheels + Hubcaps -->
<xacro:macro name="p3at_back" params="suffix reflect">
	<link name="p3at_back_${suffix}_axle">
		<inertial>
			<mass value="0.1"/>	
			<origin xyz="0 0 0"/>
			<inertia ixx="1.0" ixy="0.0" ixz="0.0"
				 iyy="1.0" iyz="0.0" izz="1.0"/>
  	 	</inertial>
	<visual name="base_visual">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry name="pioneer_geom">
			<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/p3at_meshes/axle.dae"/>
		</geometry>
		<material name="AxleGrey">
			<color rgba="0.5 0.5 0.5 1"/>
		</material>
	</visual>
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/p3at_meshes/axle.dae"/>
		</geometry>
	</collision>
	</link>
	<gazebo reference="p3at_back_${suffix}_axle">
		<material value="Gazebo/Grey"/>
	</gazebo>

	<joint name="bp3at_back_${suffix}_axle_joint" type="fixed">
		<origin xyz="-0.134 ${reflect*0.156} 0.111" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="p3at_back_${suffix}_axle"/>
	</joint>


	<link name="p3at_back_${suffix}_hub">
		<inertial>
			<mass value="0.1"/>	
			<origin xyz="0 0 0"/>
			<inertia ixx="1.0" ixy="0.0" ixz="0.0"
				 iyy="1.0" iyz="0.0" izz="1.0"/>
  	 	</inertial>
	<visual name="base_visual">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry name="pioneer_geom">
			<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/p3at_meshes/${suffix}_hubcap.dae"/>
		</geometry>
		<material name="HubcapYellow"/>
	</visual>
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/p3at_meshes/${suffix}_hubcap.dae"/>
		</geometry>
	</collision>
	</link>
	<gazebo reference="p3at_back_${suffix}_hub">
		<material value="Gazebo/Yellow"/>
	</gazebo>

	<joint name="p3at_back_${suffix}_hub_joint" type="fixed">
		<origin xyz="-0 ${reflect*0.041} 0" rpy="0 0 0"/>
		<parent link="p3at_back_${suffix}_axle"/>
		<child link="p3at_back_${suffix}_hub"/>
	</joint>

	<link name="p3at_back_${suffix}_wheel">
		<inertial>
			<mass value="0.5"/>	
			<origin xyz="0 0 0"/>
			<inertia ixx="0.012411765597" ixy="0" ixz="0"
         iyy="0.015218160428" iyz="0" izz="0.011763977943"/>
      </inertial>
	<visual name="base_visual">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry name="pioneer_geom">
			<mesh filename="package://p3at_gazebo/meshes/p3at_alt_meshes/p3at_meshes/wheel.dae"/>
		</geometry>
		<material name="WheelBlack"/>
	</visual>
	<collision>
		<origin xyz="0 0 0" rpy="${-3.1415927/2} 0 0"/>
		<geometry>
	    <!--mesh filename="package://p3at_gazebo/meshes/p3at_meshes/wheel.stl"/-->
	    <cylinder radius="0.111" length="0.075"/>
		</geometry>
	</collision>
	</link>
	<gazebo reference="p3at_back_${suffix}_wheel">
		<material value="Gazebo/Black"/>
	</gazebo>

	<joint name="p3at_back_${suffix}_wheel_joint" type="continuous">
	  <axis xyz="0 1 0"/>
    <anchor xyz="0 0 0"/>
    <limit effort="100" velocity="100" />
    <joint_properties damping="0.7"/>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<parent link="p3at_back_${suffix}_hub"/>
		<child link="p3at_back_${suffix}_wheel"/>
	</joint>

	<transmission name="p3at_back_${suffix}_wheel_tran">
		<type>transmission_interface/SimpleTransmission</type>
		<joint name="p3at_back_${suffix}_wheel_joint">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="p3at_back_${suffix}_wheel_motor">
		<hardwareInterface>EffortJointInterface</hardwareInterface>
		<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>
	
  <gazebo reference="p3at_back_${suffix}_wheel">
    <kp>1000000.0</kp> <!-- kp and kd for rubber -->
    <kd>1.0</kd>
    <mu1>10.0</mu1>
    <mu2>1.0</mu2>
    <fdir1>1 0 0</fdir1> 
    <maxVel>1.0</maxVel>
    <minDepth>0.00</minDepth>
  </gazebo>
  
  <gazebo reference="p3at_front_${suffix}_wheel">
    <kp>1000000.0</kp> <!-- kp and kd for rubber -->
    <kd>1.0</kd>
    <mu1>10.0</mu1>
    <mu2>1.0</mu2>
    <fdir1>1 0 0</fdir1> 
    <maxVel>1.0</maxVel>
    <minDepth>0.00</minDepth>
  </gazebo>

</xacro:macro>


<xacro:macro name="p3at_gazebo_ext">

<gazebo>
  <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
  <broadcastTF>true</broadcastTF>
    <updateRate>100.0</updateRate>
    <robotNamespace>/</robotNamespace>
    <leftFrontJoint>p3at_front_left_wheel_joint</leftFrontJoint>
    <rightFrontJoint>p3at_front_right_wheel_joint</rightFrontJoint>
    <leftRearJoint>p3at_back_left_wheel_joint</leftRearJoint>
    <rightRearJoint>p3at_back_right_wheel_joint</rightRearJoint>
    <wheelSeparation>0.4</wheelSeparation>
    <wheelDiameter>0.215</wheelDiameter>
    <robotBaseFrame>base_link</robotBaseFrame>
    <torque>200</torque>
    <topicName>cmd_vel</topicName>
	<!--<broadcastTF>false</broadcastTF> -->
  </plugin>
</gazebo>

</xacro:macro>
<gazebo>
  <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    <robotNamespace></robotNamespace>
	<legacyModeNS>true</legacyModeNS>
  </plugin>
</gazebo>

</robot>
